name: ulink_cli
description: CLI tool for verifying universal links and app links configuration for ULink projects
version: 0.1.0
homepage: https://ulink.ly

environment:
  sdk: ^3.6.2

dependencies:
  args: ^2.5.0
  http: ^1.2.2
  xml: ^6.5.0
  yaml: ^3.1.2
  path: ^1.9.0
  io: ^1.0.4
  plist_parser: ^0.2.6
  crypto: ^3.0.3
  uuid: ^4.0.0
  chalkdart: ^3.0.0
  cli_spin: ^1.0.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.0
  mockito: ^5.4.4
  build_runner: ^2.4.8
  fake_async: ^1.3.1
